apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/ckcd-sa/philcgithub-go-http:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/ckcd-sa/philcgithub-go-http:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: philcgithub-go-http
        chartPath: charts/philcgithub-go-http
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/ckcd-sa/philcgithub-go-http'
          image.tag: '{{.DIGEST_HEX}}'
